:verbose: false
:concurrency: 5
:pidfile: ./tmp/pids/sidekiq.pid
:queues:
  - default
:redis:
  :url: "rediss://red-cp4egei1hbls73f0gic0:XdtJb5cUIw2kQHtb0Hre6BlGutklcUC4@oregon-redis.render.com:6379" 
  